[package]
name = "bee-pow-preview3"
version = "0.1.0"
authors = ["/alex/ <Al3k5@protonmail.com>"]
edition = "2018"

[dependencies]
num_cpus = "1.11.1"
rand = "0.7.2"
tokio = "0.2.4"
crossbeam = "0.7.3"
parking_lot = "0.10.0"
